language: android
sudo: required
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28"
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "build-tools;28.0.3"
  - nvm install 12
  - node --version
  - npm i typescript react-native-cli -g --progress=false
install:
  - chmod +x ./prepare.sh
script: ./prepare.sh
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-26.0.1
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-google_apis-25
    - extra-android-support

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
node_js:
  - "12"